.github/workflows/ci.yaml, CODEOWNERS
- chore(ci): remove duplicate pdm install
- docs(ci): fix spelling
- Move to checkout v4
- Fix grammer
- Remove duplicate PDM install
- Add spacing to make my eyes not hurt
-
=> ci: update to checkout v4

.github/workflows/publish.yaml
=> ci: add publishing workflow

Makefile
- This PR corrects the URL used for installing PDM and verifies the checksum of the downloaded installer script before the installation as recommended by PDM.
=> fix: correct `install-pdm` target in the Makefile

.github/workflows/publish.yaml
=> add missing environment to publishing workflow

.github/workflows/cd.yaml, .github/workflows/ci.yaml, .gitignore, docs/changelog.rst, pyproject.toml, tools/convert_docs.sh
- Implement [Git Cliff](https://git-cliff.org/) for changelog generation based on conventional commits
There are a few ways of doing this, and I haven't ever done it for GH actions, so open to what I can fix/make better.
Also, this whole thing may be unwanted. 🤷🏽  
Docs: https://git-cliff.org/docs/github-actions/git-cliff-action
[//]: # "Please add in …
=> ci: add git cliff for changelog generation

docs/_static/css/custom.css, docs/conf.py
- Adjust light theme for users
- 
Before:
After:
=> docs: adjust theme for light mode users

.pre-commit-config.yaml
- Adds [sphinx-lint](https://github.com/sphinx-contrib/sphinx-lint) to pre-commit stack
-
=> ci: add sphinx-lint

advanced_alchemy/repository/_async.py, advanced_alchemy/repository/_sync.py, pdm.lock, sonar-project.properties, tests/integration/test_repository.py, tests/unit/test_repository.py
This PR adds support for the existing filters in the `litestar.repository.filters` file.
=> fix: temporary fix to ensure compat with litestar filters

.github/workflows/ci.yaml, Makefile, README.md, pdm.lock, pyproject.toml, tests/docker-compose.yml, tests/docker_service_fixtures.py, tests/integration/conftest.py, tests/integration/test_alembic_commands.py, tests/integration/test_repository.py
This PR adds `mssql` support using `pyodbc`
=> feat: add `mssql` support

README.md, advanced_alchemy/alembic/templates/asyncio/env.py, advanced_alchemy/alembic/templates/sync/env.py, examples/sanic.py
- This change adds examples for Sanic, FastAPI and Starlette to the Readme.
-
=> docs: adds Sanic, Starlette, and FastAPI examples to README

examples/sanic.py, sonar-project.properties
This change adds additional files to the exclusions in sonar
=> chore: add additional exclusions to sonar

sonar-project.properties
This PR adds additional exclusions for the Sonar scan
=> chore: address code duplication

advanced_alchemy/_serialization.py, advanced_alchemy/config/engine.py, advanced_alchemy/types.py
- refactor the serialization helpers into a separate module
=> refactor: move serialization helpers into one place

CONTRIBUTING.rst, README.md, advanced_alchemy/extensions/litestar/plugins/init/__init__.py
This PR addresses a bug found through sonarcloud scanning.
=> fix: remove extra __all__ methods

advanced_alchemy/extensions/litestar/__init__.py, advanced_alchemy/repository/__init__.py, pyproject.toml
This PR adds the public methods the user can use for the Litestar extension in the top level `litestar` folder in extensions.
=> feat: consolidate litestar extension imports

README.md
=> chore: include a services example in the README

README.md
Fixes:
- Add missing quotes
- Add table creation 
- Fix call to `list_and_count()` 
so as to make the examples runnable.
- 
-
=> chore: fix examples in README.md

README.md
=> chore: remove commented line from code example

advanced_alchemy/config/asyncio.py, advanced_alchemy/config/common.py, advanced_alchemy/config/sync.py, advanced_alchemy/extensions/litestar/plugins/init/config/asyncio.py, advanced_alchemy/extensions/litestar/plugins/init/config/sync.py, advanced_alchemy/extensions/litestar/plugins/init/plugin.py, tests/unit/test_extensions/test_litestar/test_init_plugin/test_asyncio.py, tests/unit/test_extensions/test_litestar/test_init_plugin/test_sync.py
- Implement a `create_all` method to deploy DDLs without Alembic.
Closes #65 
-
=> feat: add `create_all` configuration parameter for Litestar

CONTRIBUTING.rst
- `libodbc` is required to run all the tests locally.
-
=> docs: add odbc note to contributing guide

README.md
Remove extraneous ">" symbol at the end of some links.
- 
-
=> fix(docs): Update broken links in ``README.md``

Makefile, pdm.lock, pyproject.toml, tests/integration/conftest.py, tests/integration/test_alembic_commands.py, tests/integration/test_repository.py
-  Verify support for the Microsoft SQL Server database via the aioodbc driver by extending the test suite.
-  SQLAlchemy version has been updated to 2.0.23 to enable support for the same.
- Added `aioodbc` as the dialect. (`aioodbc>=0.5.0`)
-  Minor changes to the `mssql` pytest group (changed name from `mssql` to `mssql_sync`) to differentiate the sync …
=> test(aiodbc): Support for the Microsoft SQL Server database via the aioodbc driver.

advanced_alchemy/base.py
- Add missing instance  to `__all__` 
-
=> fix: add ``orm_registry`` to ``__all__``

advanced_alchemy/repository/_async.py, advanced_alchemy/repository/_sync.py, advanced_alchemy/repository/memory/_async.py, advanced_alchemy/repository/memory/_sync.py, advanced_alchemy/repository/memory/base.py, advanced_alchemy/repository/typing.py, tests/unit/test_extensions/test_litestar/conftest.py
This PR corrects an issue when the existing value of a field is None and you wish to update it.
=> fix: adds `MISSING` placeholder

Makefile, README.md, advanced_alchemy/types/encrypted_string.py, advanced_alchemy/types/json.py, pdm.lock, pyproject.toml, tests/integration/conftest.py, tests/integration/test_alembic_commands.py, tests/integration/test_repository.py
This PR does the following:
- enables tests for Oracle asyncio support 
- Does not encode/decode JSON constraints on oracledb 2.0+ where this is handled by the driver.
=> feat: `oracle` async support & json fix

advanced_alchemy/types/datetime.py
- Optional is not neccessary in there.
-
=> refactor: Remove unnecessary Optional type

advanced_alchemy/__init__.py, advanced_alchemy/exceptions.py, advanced_alchemy/repository/_util.py, advanced_alchemy/repository/memory/_async.py, advanced_alchemy/repository/memory/_sync.py, tests/unit/test_exceptions.py, tests/unit/test_repository.py
This PR renames `ConflictError` to `IntegrityError`
`ConflictError` will be removed in `v1.0.0`
=> feat: replace `ConflictError` with `IntegrityError`

README.md, docs/changelog.rst, docs/reference/index.rst, pyproject.toml
- collapse long readme sections
- add missing section into api ref. docs
- pin shibuya to `2023.10.26` due to color changes
-
=> docs: update readme, missing sections, and pin shibuya 

.pre-commit-config.yaml, advanced_alchemy/repository/_async.py, advanced_alchemy/repository/_sync.py, pdm.lock
=> fix: docstring update to fix outdated `upsert_many` info

advanced_alchemy/config/common.py
This adds `GenericAlembicConfig` to `__all__` in `advanced_alchemy.config.common.py`
Addresses a missing documentation reference issue.
-
=> docs: adds `GenericAlembicConfig` to `__all__`

.pre-commit-config.yaml, advanced_alchemy/__init__.py, advanced_alchemy/exceptions.py, advanced_alchemy/mixins/__init__.py, advanced_alchemy/mixins/unique.py, advanced_alchemy/repository/_async.py, advanced_alchemy/repository/_sync.py, advanced_alchemy/repository/_util.py, docs/reference/index.rst, docs/reference/mixins/index.rst, docs/reference/mixins/unique.rst, tests/integration/test_unique_mixin.py
This PR introduces "Unique Objects", a slight modified implementation derived from https://github.com/sqlalchemy/sqlalchemy/wiki/UniqueObject
-  Includes `UniqueMixin` featuring two methods: `as_unique_sync` and `as_unique_async`. These can be used to instantiate objects while ensuring uniqueness on some field(s).
[//]: # "Please add in issue numbers this …
=> feat: `UniqueMixin` that instantiates objects ensuring uniqueness on some field(s)

advanced_alchemy/extensions/litestar/__init__.py
This PR exposes additional exports to the litestar plugin.  This simplifies the import locations required when using the plugin.
-
=> feat: add additional exports for the `litestar` plugin

advanced_alchemy/base.py, advanced_alchemy/extensions/litestar/plugins/init/plugin.py
=> feat: adds `uuid_utils` type decoder automatically

.pre-commit-config.yaml, advanced_alchemy/base.py, advanced_alchemy/extensions/litestar/plugins/init/plugin.py, advanced_alchemy/operations.py, advanced_alchemy/types/guid.py, pdm.lock, pyproject.toml
=> fix: always use `UUID` type for compatibility

examples/standalone_json.py
- Adds a standalone example that demonstrates JSON querying using the repository methods.
=> docs(examples): Example for JSON queries

advanced_alchemy/types/guid.py
- Specifying type variable would help static analyzers do their jobs.
=> fix: specify type variable of GUID

.github/workflows/ci.yml, docs/conf.py
=> fix(ci): fix codecov

Makefile, docs/changelog.rst, docs/conf.py, docs/getting-started.rst, docs/index.rst, pdm.lock, pyproject.toml
=> docs: add landing page

.github/dependabot.yaml
=> chore(ci): configure dependabot

.github/workflows/publish.yml, CODEOWNERS, codecov.yml, sonar-project.properties
=> chore: fix code coverage and sonar

.github/workflows/ci.yml
=> fix: correct bucket name

.github/workflows/ci.yml, .github/workflows/publish.yml, .pre-commit-config.yaml, CONTRIBUTING.rst, Makefile, pdm.lock, pyproject.toml
=> chore(ci): remove `black` and enable `codecov`

advanced_alchemy/service/_converters.py, advanced_alchemy/service/_util.py, advanced_alchemy/service/typing.py, sonar-project.properties
=> fix: updated return signature for `RowMapping` results

.pre-commit-config.yaml, advanced_alchemy/extensions/litestar/alembic.py, advanced_alchemy/repository/_async.py, advanced_alchemy/repository/_sync.py, advanced_alchemy/repository/_util.py, advanced_alchemy/service/_async.py, advanced_alchemy/service/_sync.py, pdm.lock, tests/integration/test_unique_mixin.py
=> chore(lint): address `pyright` warnings where possible

advanced_alchemy/exceptions.py, advanced_alchemy/repository/_async.py, advanced_alchemy/repository/_sync.py, advanced_alchemy/service/_async.py, advanced_alchemy/service/_sync.py
=> fix: loader options passing

advanced_alchemy/repository/_async.py, advanced_alchemy/repository/_sync.py
=> fix: don't mutate statement in place

advanced_alchemy/filters.py
=> fix: add additional Filter classes to `__all__`

.github/workflows/ci.yml, .pre-commit-config.yaml, advanced_alchemy/repository/__init__.py, advanced_alchemy/repository/_async.py, advanced_alchemy/repository/_sync.py, advanced_alchemy/repository/memory/_async.py, advanced_alchemy/repository/memory/_sync.py, advanced_alchemy/service/__init__.py, advanced_alchemy/service/_async.py, advanced_alchemy/service/_sync.py, advanced_alchemy/service/_util.py, advanced_alchemy/service/typing.py, advanced_alchemy/types/encrypted_string.py, advanced_alchemy/types/json.py, pdm.lock, pyproject.toml, tests/fixtures/uuid/services.py, tests/integration/test_repository.py, tests/integration/test_sqlquery_service.py
- Adds `filters` args for single row operations.  
```python
await repo.get_one(Model.value.in_('PENDING','RUNNING'), thing="my value")
```
- Type improvements
=> feat: single row operations are filterable

advanced_alchemy/extensions/litestar/plugins/init/plugin.py, pyproject.toml
=> fix: namespace signature override

.pre-commit-config.yaml, advanced_alchemy/config/common.py, advanced_alchemy/extensions/litestar/plugins/init/config/asyncio.py, advanced_alchemy/extensions/litestar/plugins/init/config/sync.py, advanced_alchemy/extensions/litestar/plugins/init/plugin.py, advanced_alchemy/filters.py, advanced_alchemy/service/_util.py, advanced_alchemy/service/typing.py, pdm.lock, pyproject.toml, tests/unit/test_extensions/test_litestar/conftest.py
=> feat: optimize type adapter call & multi-config fixes

.pre-commit-config.yaml, advanced_alchemy/exceptions.py, advanced_alchemy/repository/_async.py, advanced_alchemy/repository/_sync.py, advanced_alchemy/types/json.py, pdm.lock, pyproject.toml, tests/docker_service_fixtures.py, tests/integration/test_repository.py
=> feat: improved `IntegrityError` details parsing

advanced_alchemy/base.py
=> feat: add `TZ` validator to `AuditModel`

advanced_alchemy/base.py, advanced_alchemy/exceptions.py, pyproject.toml
=> fix: simplify string concatenation for error handling

advanced_alchemy/extensions/litestar/plugins/init/config/asyncio.py, advanced_alchemy/extensions/litestar/plugins/init/config/sync.py
- In some of the Litestar main repo tests, there were failures (likely) due to some sort of race condition.  This additional conditional ensures that there is a `dispose` function that can be called.
=> fix: check engine before disposing

README.md, advanced_alchemy/base.py, advanced_alchemy/types/__init__.py, advanced_alchemy/types/guid.py, pdm.lock, pyproject.toml, tests/fixtures/uuid/models.py, tests/integration/conftest.py
This PR adds an optional Nano ID base model integration.
=> feat: add optional nanoid base models

docs/changelog.rst
- Fix spelling errors in GitHub links: `gihub.com...` -> `github.com...`
=> chore: fix spelling errors in GitHub links

.gitignore, Makefile, advanced_alchemy/extensions/litestar/plugins/init/plugin.py, advanced_alchemy/repository/_async.py, advanced_alchemy/repository/_sync.py, tests/unit/test_extensions/test_litestar/test_init_plugin/test_common.py
=> fix: namespace signature pollution

advanced_alchemy/filters.py
=> docs: updated docstring for `NotInSearchFilter` and `SearchFilter`

.pre-commit-config.yaml, advanced_alchemy/repository/_async.py, advanced_alchemy/repository/_sync.py, advanced_alchemy/service/_async.py, advanced_alchemy/service/_sync.py, uv.lock
=> feat: adds default load options at class definition

pyproject.toml, uv.lock
=> chore(release): prepare for `v0.22.2`

advanced_alchemy/config/types.py, advanced_alchemy/extensions/litestar/alembic.py, advanced_alchemy/extensions/litestar/plugins/init/plugin.py, advanced_alchemy/repository/_async.py, advanced_alchemy/repository/_sync.py, advanced_alchemy/repository/_util.py, advanced_alchemy/service/_async.py, advanced_alchemy/service/_sync.py, advanced_alchemy/service/_typing.py, advanced_alchemy/service/_util.py, advanced_alchemy/service/pagination.py, advanced_alchemy/service/typing.py, advanced_alchemy/utils/dataclass.py, docs/conf.py, examples/fastapi.py, examples/litestar/litestar_service.py, pyproject.toml, sonar-project.properties, uv.lock
- Corrects an issue with python 3.8 support
- Closes #281
=> fix: typing hint adjustment for `service.typing`

advanced_alchemy/exceptions.py, advanced_alchemy/repository/_async.py, advanced_alchemy/repository/_sync.py, pyproject.toml, tests/integration/test_association_proxy.py, uv.lock
=> feat: lambda caching fixes

.pre-commit-config.yaml, advanced_alchemy/exceptions.py, advanced_alchemy/types/encrypted_string.py, tests/fixtures/bigint/models.py, tests/fixtures/uuid/models.py, tests/integration/test_repository.py, uv.lock
=> feat: add max length for encrypted string

docs/_static/versions.json, docs/conf.py, pyproject.toml, uv.lock
=> chore(release): prepare for `v0.25.0`

.github/labeler.yml, .github/workflows/docs.yml, .gitignore, docs/_static/versions.json, tools/build_docs.py
=> chore: additional documentation build updates

docs/reference/base.rst, docs/reference/config/asyncio.rst, docs/reference/config/common.rst, docs/reference/config/engine.rst, docs/reference/config/sync.rst, docs/reference/config/types.rst, docs/reference/service.rst, docs/reference/utils.rst
=> fix: allow documentation indexing

docs/reference/extensions/litestar/cli.rst, docs/reference/extensions/litestar/index.rst, docs/reference/extensions/litestar/plugins.rst
=> fix: more documentation updates

advanced_alchemy/extensions/litestar/alembic.py, advanced_alchemy/extensions/litestar/cli.py, advanced_alchemy/extensions/litestar/exception_handler.py, advanced_alchemy/extensions/litestar/plugins/init/config/asyncio.py, advanced_alchemy/extensions/litestar/plugins/init/config/sync.py, advanced_alchemy/extensions/litestar/plugins/init/plugin.py, sonar-project.properties, tests/unit/test_extensions/test_litestar/test_init_plugin/test_asyncio.py, tests/unit/test_extensions/test_litestar/test_init_plugin/test_sync.py, uv.lock
This adds a configuration option to automatically enable an excpetion handler for Repository errors. 
This will update the exception handler if you do not have one already configured for the RepositoryException class
=> feat: add default exception handler for `litestar` integration

advanced_alchemy/base.py
=> fix: revert to `Optional` style type syntax

advanced_alchemy/repository/_async.py, advanced_alchemy/repository/_sync.py
=> fix(typing): fix typing of id_attribute fields

docs/usage/frameworks/litestar.rst
This PR adds documentation for creating session in LiteStar using Advanced Alchemy
=> docs: added information about accessing sessions

.pre-commit-config.yaml, advanced_alchemy/base.py, advanced_alchemy/config/common.py, docs/PYPI_README.md, docs/conf.py, docs/getting-started.rst, docs/reference/base.rst, docs/reference/mixins/index.rst, docs/usage/frameworks/litestar.rst, pyproject.toml, uv.lock
=> feat: updated `advanced_alchemy.base` reference docs

advanced_alchemy/filters.py, docs/_static/custom.css
fix: doc corrects header text sizing issues for small devices
=> fix(docs): adjust title formatting for smaller screens

docs/usage/index.rst, docs/usage/types.rst
Add documentation part for the types
It's missing more insight for the EncryptedString I think
=> docs: add types documentation

docs/usage/modeling.rst, docs/usage/services.rst
Created a section to define a custom model. 
Maybe the example is not correct but could not think of a specific use case, if you have any I can update this.
=> docs: Add doc for creating a custom model

Makefile
running `make install` blew away my _entire_ pre-commit cache (!) which i don't think was the intention.
=> chore: don't clear pre-commit cache

docs/conf.py, docs/usage/frameworks/fastapi.rst, docs/usage/frameworks/litestar.rst, docs/usage/modeling.rst, docs/usage/services.rst
while reading through the example code in the Services usage docs, i had a hard time understanding what method calls were coming from where due to the lack of imports and a few incorrect usages. this fixes those, as well as adds a few more links
=> docs: clarifications to services and modeling docs

Makefile
the same changes i proposed in litestar:
- https://github.com/litestar-org/litestar/pull/3956
- https://github.com/litestar-org/litestar/pull/3957
- https://github.com/litestar-org/litestar/pull/3958
=> chore: update `docs-serve`  to find a port and open the browser

advanced_alchemy/base.py, docs/conf.py, docs/getting-started.rst, docs/index.rst, docs/reference/mixins/index.rst, docs/usage/frameworks/litestar.rst, docs/usage/modeling.rst, docs/usage/repositories.rst, docs/usage/types.rst
- various copy edits and added links to references
=> docs: various copy edits and linking improvements

advanced_alchemy/extensions/flask/__init__.py, advanced_alchemy/extensions/flask/alembic.py, advanced_alchemy/extensions/flask/config.py, advanced_alchemy/extensions/flask/service.py, tests/unit/test_extensions/test_flask.py
This corrects an issue that caused the Flask extension to use the incorrect serializer for encoding JSON
=> fix(flask): implement default schema serializer

docs/usage/modeling.rst
docs: rename NanoidBase -> NanoIDBase
Update docs, rename NanoidBase -> NanoIDBase
-
=> docs: rename NanoidBase -> NanoIDBase

tools/sphinx_ext/changelog.py
Should link to the AA repo, not litestar :)
=> fix(docs): Fix reference in `changelog.py`

advanced_alchemy/repository/_async.py, advanced_alchemy/repository/_sync.py
Fix query repositories list method according to [documentation](https://docs.advanced-alchemy.litestar.dev/latest/usage/repositories.html#query-repository).
Now its return a list of tuples with values instead of first column of the query.
=> fix(#338): Query repository list method for custom queries

advanced_alchemy/repository/_async.py, advanced_alchemy/repository/_sync.py, advanced_alchemy/repository/memory/_async.py, advanced_alchemy/repository/memory/_sync.py, advanced_alchemy/service/_async.py, advanced_alchemy/service/_sync.py
Exposes the `uniquify` flag in all functions on the repository and add to the service
=> feat: add `uniquify` to service and repo

advanced_alchemy/__metadata__.py, advanced_alchemy/base.py, advanced_alchemy/service/_util.py
Improves the default serializer so that it handles various types a bit better
=> feat: improved default serializer

advanced_alchemy/repository/_async.py, advanced_alchemy/repository/_sync.py
Remove `limit` and `offset` from count statement
=> fix: remove `limit` and `offset` from count statement

advanced_alchemy/extensions/litestar/plugins/serialization.py, docs/changelog.rst, pyproject.toml, uv.lock
Use `SerializationPlugin` instead of `SerializationPluginProtocol`
=> feat(litestar): Use `SerializationPlugin`

docs/usage/index.rst, docs/usage/utilities.rst
Remove the unused section utilities for 1.0
=> docs: removed utilities page in usage

docs/reference/repository.rst, docs/usage/database_seeding.rst, docs/usage/index.rst
Do not know if the examples are correct as they are seeding on app start
Closes #402
=> docs: add fixtures/database seeding documentation

docs/usage/frameworks/flask.rst
Refactors Flask documentation to:
- Simplify configuration and initialization of AdvancedAlchemy
- Update code examples to use modern SQLAlchemy 2.0 syntax
- Add comprehensive example of service implementation with CRUD operations
- Improve readability and demonstrate key features of Advanced Alchemy with Flask
=> docs(flask): update Flask documentation with simplified examples and best practices

advanced_alchemy/filters.py
Removes some stringified representations to help with the forward resultion of `datetime` and `Collection`.
=> fix: prevent forward resolution issues

.pre-commit-config.yaml, typos.toml
=> refactor: migrate to typos

docs/changelog.rst
- update changelog.rst from `0.x Changelog` to `1.x Changelog`
=> chore: update changelog.rst

docs/usage/database_seeding.rst, docs/usage/frameworks/flask.rst, docs/usage/modeling.rst, docs/usage/repositories.rst, docs/usage/types.rst
=> chore: make docs consistent

.gitignore, .pre-commit-config.yaml, advanced_alchemy/extensions/litestar/providers.py, advanced_alchemy/repository/memory/_async.py, advanced_alchemy/repository/memory/_sync.py, advanced_alchemy/utils/text.py, tests/unit/test_extensions/test_litestar/test_providers.py, uv.lock
Implements the following filters as configurable options:
- NotInCollection
- Collection
Search now also accepts a set of strings in addition to a comma delimmited list.
=> feat(litestar): additional filter configuration options

docs/_static/custom.css, docs/index.rst
=> fix: btn ui

examples/litestar/litestar_service.py
=> fix: updated example `litestar_service.py` model

advanced_alchemy/extensions/litestar/providers.py, tests/unit/test_extensions/test_litestar/test_providers.py
Update the Litestar service provider to use dynamic session dependency key
=> fix(litestar): update service provider to use dynamic session dependency key

.pre-commit-config.yaml, advanced_alchemy/types/file_object/_typing.py, advanced_alchemy/types/file_object/file.py, examples/fastapi/fastapi_fileobject.py, examples/fastapi/fastapi_service_full.py, pyproject.toml, tests/unit/test_extensions/test_fastapi/test_providers.py, tests/unit/test_file_object.py, typos.toml, uv.lock
File object will now serialize properly in pydantic.
More complete FastAPI examples added.
=> fix: FileObject native Pydantic Core integration

advanced_alchemy/filters.py, tests/integration/test_filters.py
Raise exception if filter operator does not exist in operators_map
Fixes #453
=> fix: raise if filter operator is not in `operators_map`

advanced_alchemy/mixins/bigint.py, sonar-project.properties
BigIntPrimaryKey will now respect schema names.
Fixes #466
=> fix: BigIntPrimaryKey does not respect schema names

advanced_alchemy/types/password_hash/argon2.py, advanced_alchemy/types/password_hash/passlib.py, advanced_alchemy/types/password_hash/pwdlib.py
This update adds __all__ exports for the Argon2, Passlib, and Pwdlib hashing backends, improving module visibility and usability.
=> feat(types): add __all__ exports for password hashing backends

examples/fastapi/fastapi_fileobject.py, examples/litestar/litestar_fileobject.py
- Add fileobject example for litestar
=> docs: add fileobject example for litestar

docs/usage/frameworks/litestar.rst
- fix according to https://github.com/litestar-org/litestar-fullstack/blob/0996536189cf48c0b7ce8c2c2600cb439968a377/src/app/domain/accounts/controllers/users.py#L49
=> fix: correct typing issue in `litestar` example

CONTRIBUTING.rst
- Update `Creating a new release` instructions
- Preview: https://github.com/Harshal6927/advanced-alchemy/blob/new-release-doc/CONTRIBUTING.rst
=> chore: update `Creating a new release` instructions

advanced_alchemy/service/_typing.py, advanced_alchemy/service/_util.py, advanced_alchemy/service/typing.py
Corrects an issue where the type hint was incorrect when `attrs` or `cattrs` were not installed.
=> fix: `to_schema` and `attrs` type hint correction

docs/changelog.rst, docs/usage/database_seeding.rst, docs/usage/frameworks/fastapi.rst, docs/usage/frameworks/flask.rst, docs/usage/frameworks/litestar.rst, examples/fastapi/fastapi_fileobject.py, examples/fastapi/fastapi_filters.py, examples/fastapi/fastapi_service.py, examples/fastapi/fastapi_service_full.py, examples/flask/flask_services.py, examples/litestar/litestar_fileobject.py, examples/litestar/litestar_repo_only.py, examples/litestar/litestar_service.py, examples/sanic.py, examples/standalone.py, examples/standalone_json.py
=> chore(docs): make docs consistent

docs/changelog.rst, pyproject.toml, uv.lock
=> chore(release): bump to v1.6.1

advanced_alchemy/cli.py, tests/unit/fixtures.py, tests/unit/test_cli.py
Correctly allow loading configuration from the current directory
=> feat(cli): enable loading config from working directory

docs/usage/frameworks/litestar.rst, examples/litestar/litestar_fileobject.py
- Fix litestar fileobject example
=> fix: litestar fileobject example

advanced_alchemy/repository/_util.py, tests/unit/test_repository.py
Property correction for updates
=> fix: property correction

advanced_alchemy/extensions/starlette/config.py, advanced_alchemy/utils/sync_tools.py, pyproject.toml
=> chore(logging): make log consistent fastapi
