litestar-org/advanced-alchemy

advanced_alchemy/config/engine.py
- This PR reuses the `Encoder` and `Decoder` instances when using `msgspec` as the JSON serializer/deserializer.
=> fix: reuse msgspec Encoder and Decoder instances

advanced_alchemy/extensions/litestar/alembic.py, pyproject.toml
This fix corrects the reference to the `sqlalchemy_config` for Litestar integration.
=> fix: correct reference to plugin for litestar

advanced_alchemy/alembic/templates/asyncio/env.py
This PR corrects an issue where Alembic will not detect models and generates an empty migration.
=> fix: use `asyncio.run`

.pre-commit-config.yaml, advanced_alchemy/repository/_async.py, advanced_alchemy/repository/_sync.py, pdm.lock, pyproject.toml, sonar-project.properties, tests/integration/test_alembic_commands.py, tests/integration/test_repository.py, tests/unit/test_repository.py
This PR removes the re-exported filters in the repository for Litestar.
This has been addressed on the Litestar side and is no longer required.
=> fix: remove extra filter imports

.pre-commit-config.yaml, Makefile
- add the `default_install_hook_types` to get `pre-commit` to install the various hooks through the `pre-commit install` command
- install `pre-commit` hooks as part of the `install` target in the Makefile
=> chore: install all pre-commit hook types by default

advanced_alchemy/extensions/litestar/plugins/init/config/asyncio.py, advanced_alchemy/extensions/litestar/plugins/init/config/sync.py, tests/unit/test_extensions/test_litestar/test_init_plugin/test_asyncio.py, tests/unit/test_extensions/test_litestar/test_init_plugin/test_sync.py
Introduction of a new factory function `autocommit_handler` to create handlers that supports:
- handling all redirects (3XX) with performing a commit
- specifying custom sets of status codes for commit and/or rollback
This might be desirable for MPAs, where it is quite common to use the [PRG pattern](https://en.wikipedia.org/wiki/Post/Redirect/Get) - after a successful form submission, a redirect response is issued to prevent …
=> feat: configurable autocommit handler factory function for Litestar plugin

advanced_alchemy/repository/_async.py, advanced_alchemy/repository/_sync.py, tests/integration/test_repository.py, tests/unit/test_repository.py
Fixes #51
Bug: CollectionFilter returns all entries if values is empty
a simple `1=-1` is appended into the `where` clause when an empty list is passed into the `in` statement.
=> fix: CollectionFilter returns all entries if values is empty

.pre-commit-config.yaml, advanced_alchemy/repository/_async.py, advanced_alchemy/repository/_sync.py, pdm.lock, pyproject.toml
This PR set the Postgres dialects to prefer to use an `ANY` instead of an `IN` for filtering a collection fo results.  
```sql
select id
from my_table
where id = ANY(:1)
```
instead of
```sql
select id
from my_table
where id in (:1, :2, :3, ...)
```
This has the additional benefit of allowing us to avoid hitting the max bind parameters values of the …
=> feat: prefer `ANY` over `IN` for `postgres`

.github/workflows/test.yaml, advanced_alchemy/repository/_async.py, advanced_alchemy/repository/_sync.py, advanced_alchemy/service/_async.py, advanced_alchemy/service/_sync.py, advanced_alchemy/utils/deprecation.py, tests/integration/test_repository.py
This PR adds a deprecation warning for the `get_or_create` function in the repository.
`get_or_create` was not a correct representation of what the function did.  `get_or_upsert` is the udpated name.
=> feat: deprecate `get_or_create` in favor of `get_or_upsert`

advanced_alchemy/repository/_async.py, advanced_alchemy/repository/_sync.py, advanced_alchemy/service/_async.py, advanced_alchemy/service/_sync.py, tests/integration/test_repository.py
This PR prevents the primary key from being overrwitten with `None` when using the service without the `item_id` parameter.
=> fix: do not set `id` with `item_id` when `None`

advanced_alchemy/service/_async.py, advanced_alchemy/service/_sync.py, tests/integration/test_repository.py
This PR raises a repository error when you call the service `update` method without an `item_id` and without a value for the ID attribute.
This ensures you are operating with data that can actually be updated.
=> feat: verify the service has an identity before updating.

advanced_alchemy/extensions/litestar/dto.py, tests/unit/test_extensions/test_litestar/test_dto_integration.py
Examples of such fields are `ColumnClause` and `Label`, these are generated when using `sqlalchemy.func`
- Fix SQLAlchemy dto generation for litestar when using models that have fields that are not instances of `Column`. Such fields arise from using expressions such as `func`.
[//]: # "Please add in issue numbers this pull request will close, if …
=> fix: sqlalchemy dto for models non `Column` fields

advanced_alchemy/base.py, advanced_alchemy/repository/_util.py
- [-] (If applicable) The prose documentation has been updated to reflect the changes introduced by this PR
- [-] (If applicable) The reference documentation has been updated to reflect the changes introduced by this PR
Positional name's can't find by column model.__table__.columns.
"Fixes #74"
=> fix: reference column names from `Mapper` object in `model_from_dict`

advanced_alchemy/repository/_async.py, advanced_alchemy/repository/_sync.py, advanced_alchemy/service/_async.py, advanced_alchemy/service/_sync.py, tests/integration/test_repository.py, tests/unit/test_repository.py
Adds `get_and_update` functions to the repository.  If the record is not found, and exception is raised. 
-------
Now that we've renamed the method to `get_or_upsert`, there have been a few cases where I have needed to temporarily disable one of the operations on the endpoint.  @JacobCoffee asked for something similar recently as well.
Rather than add a `get_and_update` method that disables the "insert" operation of the `get_or_upsert`, I am proposing we have an additional parameter (and rename an existing one) to optionally disable the create and update operations on the function.
This PR:
- renames the `upsert` parameter to `update`.
- adds a `create` parameter
Both of these default to `True` to ensure current functionality stays consistent.
=> feat: add `get_and_update` to the repository and services

.pre-commit-config.yaml, advanced_alchemy/__init__.py, advanced_alchemy/alembic/templates/asyncio/env.py, advanced_alchemy/alembic/templates/sync/env.py, advanced_alchemy/extensions/litestar/__init__.py, pdm.lock
This PR re-exports all configurations at the Litestar extension level. 
Previously, you would have to import from multiple files.  Now, you can import everything you need from the main `litestar` module.
=> feat: re-export modules to make importing easier

pdm.lock, pyproject.toml
Greenlet is a required dependency for SQLAlchemy Asyncio on OSX.  This change will automatically install `greenlet` for this platform.
=> fix: adds `greenlet` as a dependencies for Mac OS

advanced_alchemy/repository/_async.py, advanced_alchemy/repository/_sync.py, tests/integration/test_repository.py
This PR changes the `upsert_many` logic.
Previously, it had no way of merging the identify of the existing objects back to the data being inserted.  This change will merge the identiy value on to the data to be udpated.
=> fix: change `upsert_many` behavior

advanced_alchemy/types.py
This implements the `python_type` property for `DateTimeUTC`.
This is used by other libraries such as `polyfactory`.  It was previously raising a `NotImplementedError` instead of returning a `datetime` type.
=> fix: adds the `python_type` property.  

advanced_alchemy/service/_async.py, advanced_alchemy/service/_sync.py
-  The `str` type hint was missing from the service declaration.  This needs to be added to align with the repositoryl
-
=> fix: add `str` to `match_fields` type hint

advanced_alchemy/extensions/litestar/_utils.py, advanced_alchemy/extensions/litestar/plugins/init/config/asyncio.py, advanced_alchemy/extensions/litestar/plugins/init/config/sync.py, tests/unit/test_extensions/test_litestar/test_init_plugin/test_asyncio.py, tests/unit/test_extensions/test_litestar/test_init_plugin/test_common.py, tests/unit/test_extensions/test_litestar/test_init_plugin/test_sync.py
Litestar has deprecated external use of their scope state namespace.
This PR implements scope state utilities that manage a namespace unique to advanced-alchemy.
Closes #103
=> refactor: use internal utilities for scope state storage.

advanced_alchemy/repository/memory/_async.py, advanced_alchemy/repository/memory/_sync.py, advanced_alchemy/service/_async.py, advanced_alchemy/service/_sync.py
The `ColumnElement[bool]` type was missing from the service `count` and `list_and_count` method.
=> fix: correct `count` and `list_and_count` signatures

advanced_alchemy/alembic/templates/asyncio/script.py.mako, advanced_alchemy/alembic/templates/sync/script.py.mako, advanced_alchemy/types/encrypted_string.py
Updates the alembic template so that it will properly generate the DDL for Encrypted types.
Without the default key, the Alembic templates will complain- even though the key is not actually needed to deploy the DDLs
=> fix: add Alembic template for Encrypted String

advanced_alchemy/types/datetime.py
- This PR introduces a modification to the `DateTimeUTC` class, changing the generic type to allow the column to be either `datetime.datetime` or `None`. This adjustment would be useful for static analyzers to perform their tasks without raising errors.
- `DateTimeUTC(TypeDecorator)` -> `DateTimeUTC(TypeDecorator[TypeDecorator[datetime.datetime | None])` …
=> fix: Specify generic type

advanced_alchemy/repository/_async.py, advanced_alchemy/repository/_sync.py, tests/integration/test_lambda_stmt.py
This PR disable the tracking of statements that alter the column projections on the following functions:
- count
- list_and_count (basic & window)
This statement was causing errors when re-using lambdas for multiple queries.
Resolves #126 #120
=> fix: adjust `lambda_stmt` statement tracking

README.md, advanced_alchemy/base.py, advanced_alchemy/extensions/litestar/plugins/init/plugin.py, advanced_alchemy/extensions/sanic.py, advanced_alchemy/service/typing.py, advanced_alchemy/types/__init__.py, advanced_alchemy/types/guid.py, pdm.lock, pyproject.toml
This PR addresses an issue with type hints when `uuid-utils` is not installed.
```shell
❯ pdm run pip uninstall uuid-utils
Found existing installation: uuid_utils 0.6.1
Uninstalling uuid_utils-0.6.1:
Would remove:
.../.venv/lib/python3.12/site-packages/uuid_utils-0.6.1.dist-info/*
.../.venv/lib/python3.12/site-packages/uuid_utils/*
Proceed (Y/n)? y
Successfully uninstalled uuid_utils-0.6.1
❯ pdm run pyright -p pyproject.toml advanced_alchemy/base.py
0 errors, 0 warnings, 0 informations 
❯ pdm run pyright -p pyproject.toml advanced_alchemy/types/guid.py
0 errors, 0 warnings, 0 informations 
```
=> fix: adjusted type hints for `UUID` when `uuid-utils` is not installed

advanced_alchemy/repository/_util.py, tests/unit/test_extensions/test_litestar/test_litestar_re_exports.py
`wrap_sqlalchemy_exception()` was moved from `repository._util` to `exceptions`, however it is still imported downstream by litestar from the original location.
This PR adds an alias to the function in `repository._util` for backward compat with litestar.
- 
[//]: # …
=> fix: moved function breaks Litestar imports.

advanced_alchemy/base.py, tests/models_bigint.py, tests/models_uuid.py
When using mixins that include their own tablerags, it is difficult to append info into the model such as a comment.
This PR adds a helper function to merge the args together.
-
=> feat: merge table argument helper

.github/workflows/test.yml, .pre-commit-config.yaml, Makefile, advanced_alchemy/extensions/litestar/plugins/init/plugin.py, advanced_alchemy/repository/_async.py, advanced_alchemy/repository/_sync.py, pdm.lock, pyproject.toml, tests/integration/test_repository.py, tests/unit/test_repository.py
=> fix: `upsert` with no identity field populated

docs/conf.py
- Title shows up as "Litestar Framework", fixed to make it show "Advanced Alchemy""
=> fix: html_title

advanced_alchemy/base.py
- fixed behavior for `updated_at` field when updating the model
When the model is created, it is not necessary to fill in the 'updated_at` field.
But when updating the model, it needs to be updated automatically.
- hotfix
Returned the default value for the field.
=> fix: fixed behavior for `updated_at` field when updating the model

README.md, advanced_alchemy/service/pagination.py, docs/conf.py
This PR addresses a type hint compatibility issue for Python 3.8
=> fix: type hint for 3.8 support

advanced_alchemy/base.py, tests/models_bigint.py, tests/models_uuid.py
Uses `__bases__` of the DeclaredAttr type to get `__table_args__` of classes in the mixin hierarchy.
=> refactor!: use __bases__ to merge mixin table args

advanced_alchemy/base.py, advanced_alchemy/repository/__init__.py, advanced_alchemy/service/_converters.py, advanced_alchemy/service/_util.py, pdm.lock, tests/integration/test_sqlquery_service.py, tests/models_bigint.py
=> fix: `to_schema` inocrrectly checks for `ModelMetaclass` instead of `BaseModel`

.pre-commit-config.yaml, advanced_alchemy/repository/_async.py, advanced_alchemy/repository/_sync.py, advanced_alchemy/repository/_util.py, pdm.lock, pyproject.toml, tests/integration/test_lambda_stmt.py, tests/integration/test_loader_and_execution_options.py, tests/integration/test_repository.py, tests/models_uuid.py, tests/unit/test_repository.py
=> fix: set `options` and `execution_options` before calling `lambda_stmt`

advanced_alchemy/extensions/litestar/plugins/init/config/asyncio.py, advanced_alchemy/filters.py, advanced_alchemy/repository/_async.py, advanced_alchemy/repository/_sync.py, advanced_alchemy/repository/_util.py, advanced_alchemy/repository/memory/_async.py, advanced_alchemy/repository/memory/_sync.py, advanced_alchemy/service/_async.py, advanced_alchemy/service/_sync.py, tests/unit/test_repository.py
This refactors the FilterTypes to a more extensible design.  You can now subclass StatementFilter to create your own custom repository filters.
=> feat: create a `StatementFilter` type for repository filters

advanced_alchemy/filters.py, advanced_alchemy/repository/memory/_async.py, advanced_alchemy/repository/memory/_sync.py
=> refactor(search_filter): Removes some redundant code

advanced_alchemy/repository/_async.py, advanced_alchemy/repository/_sync.py, advanced_alchemy/repository/memory/_async.py, advanced_alchemy/repository/memory/_sync.py, advanced_alchemy/service/_async.py, advanced_alchemy/service/_sync.py, advanced_alchemy/service/_util.py, advanced_alchemy/service/typing.py, tests/fixtures/bigint/services.py
=> fix: implement library installed check

advanced_alchemy/service/_async.py, advanced_alchemy/service/_sync.py, advanced_alchemy/service/typing.py, sonar-project.properties, tests/fixtures/bigint/services.py, tests/fixtures/uuid/services.py, tests/integration/test_sqlquery_service.py
This PR allows the service layer to accept MsgSpec Struct or Pydantic BaseModels in addition to dictionaries and SQLAlchemy models.
The service will attempt to convert the Pydantic or Msgspec model to a dictionary before calling the repository methods.
This allows a few lines to be removed in places like HTTP routes because you no longer need to convert the model to a dict before calling the service.
=> feat: services accept BaseModels and Structs

advanced_alchemy/repository/_async.py, advanced_alchemy/repository/_sync.py, advanced_alchemy/service/_async.py, advanced_alchemy/service/_sync.py, advanced_alchemy/service/typing.py, pyproject.toml, tests/fixtures/bigint/services.py, tests/fixtures/uuid/services.py, tests/integration/test_sqlquery_service.py
This PR:
- Reverts the previous `to_schema` implementation in the service layer.  This will need to be rethought as it requires too many overloads to any customized service function.  
- Ensures that the filter values for `upsert_many` is a unique list.  This is useful when you are merging a large amount of objects on a foreign key.  The lookup will only contain a single unique entry for each key instead of one for each row.
- Adds a `schema_to_dict` method to convert incoming Pydantic or Msgspec models to dictionaries
- Adds additional type guard helpers to check for a field in a dictionary, Struct, or BaseModel
=> feat!: revert `to_schema` overloads & optimize `upsert_many`

advanced_alchemy/service/typing.py
-
`FailFast` raises an exception in cases where it can't be applied to a schema.  Disabling this until the behavior can be better understood.
=> fix: disable `FailFast` usage

.pre-commit-config.yaml, advanced_alchemy/extensions/litestar/__init__.py, advanced_alchemy/extensions/litestar/_utils.py, advanced_alchemy/extensions/litestar/dto.py, advanced_alchemy/extensions/litestar/plugins/init/config/asyncio.py, advanced_alchemy/extensions/litestar/plugins/init/config/sync.py, advanced_alchemy/repository/_async.py, advanced_alchemy/repository/_sync.py, advanced_alchemy/service/_async.py, advanced_alchemy/service/_sync.py, advanced_alchemy/service/typing.py, pdm.lock, tests/fixtures/uuid/services.py, tests/helpers.py, tests/integration/test_association_proxy.py, tests/unit/test_extensions/test_litestar/test_dto.py, tests/unit/test_extensions/test_litestar/test_dto_integration.py, tests/unit/test_repository.py
This PR:
- correct an issue with the default order by contructor method
- Adds support for `DTOData` in the service layer.  It will auto-convert these types to instances.
=> feat: `DTOData` support in services

advanced_alchemy/base.py
It's imposible to get_type_hints() otherwise without monkey patching or other shenanigans due to `FromClause` not being imported in runtime.
About `__name__` and `__mapper__`. With monkey patching get_type_hints() on BigIntAuditBase results into:
` {'created_at': sqlalchemy.orm.base.Mapped[datetime.datetime], 'updated_at': sqlalchemy.orm.base.Mapped[datetime.datetime], '__name__': <class 'str'>, '__mapper__': sqlalchemy.orm.mapper.Mapper[typing.Any], '__table__': <class 'sqlalchemy.sql.selectable.FromClause'>}`
clearly `__name__`, `__mapper__`, `__table__` should not be there
```
from typing import get_type_hints
from advanced_alchemy.base import BigIntAuditBase
get_type_hints(BigIntAuditBase)
```
https://github.com/litestar-org/advanced-alchemy/issues/242
=> refactor: Fix types for ModelProtocal and BasicAttributes

advanced_alchemy/operations.py, advanced_alchemy/repository/_async.py, advanced_alchemy/repository/_sync.py, tests/unit/test_repository.py
It turns out that the existing merge code in the `operations` folder will require a bit more work before it's ready to be used in the repository.  
I've left the Merge PR open with this full code and I'm proposing we remove some of these long standing unused references.  We can re-add this when it's ready to be used again.
=> feat: remove unfinished merge operation

advanced_alchemy/extensions/sanic.py
binds session into sanic extension as expected
in the original code, session maker was defined and then the dependency for session overwrites it with a session maker as the type.  this seems non-ideal -- you can't get the session maker and when you ask for the session maker you get a session object
instead, this looks at the sessionmaker `class_` property for adding the sanic dependency
fixes #267
=> fix(sanic): bind session to session class instead of to the session maker

advanced_alchemy/exceptions.py
Swap the variable names for DUPLICATE_KEY_REGEXES and FOREIGN_KEY_REGEXES to correctly match their contents. 
This ensures that the error detection for duplicate keys and foreign key violations works as intended across different database backends.
#262
=> fix: correct regex mappings for duplicate and foreign key errors

advanced_alchemy/extensions/litestar/cli.py
Changes the argument name so that it matches the name given in `click.option`.
=> fix(cli): Change the argument name back

advanced_alchemy/service/typing.py
Fixes typing issues in service
https://github.com/litestar-org/advanced-alchemy/issues/265
This still doesn't solve the problem of UnknownVariableType if the subtypes of ModelDictT are not installed (eg: Pydantic)
But at least it solves the problem of incompatibilities when they are installed
=> feat: Improved typing of `ModelDictT`

advanced_alchemy/service/_async.py, advanced_alchemy/service/_sync.py, advanced_alchemy/utils/fixtures.py
`anyio` is installed with nearly all web frameworks, so I'd prefer to not add it as a required dependency.
However, when running standalone, you would receive this exception for fixtures
=> fix: make sure `anyio` is optional

advanced_alchemy/extensions/litestar/dto.py, tests/unit/test_extensions/test_litestar/test_dto.py
The Litestar DTO has been enhanced with:
- The SQLAlchemyDTOConfig's `exclude`, `include`, and `rename_fields` fields will now accept string or `InstrumentedAttributes`
- DTO supports `WriteOnlyMapped` and `DynamicMapped`
Closes #306 and #250
=> feat: `litestar` DTO enhancements

advanced_alchemy/extensions/litestar/plugins/init/plugin.py, advanced_alchemy/mixins/nanoid.py, advanced_alchemy/mixins/uuid.py, docs/conf.py, examples/fastapi.py, examples/litestar/litestar_repo_only.py, examples/litestar/litestar_service.py, examples/sanic.py, pyproject.toml, tests/integration/test_loader_and_execution_options.py, tests/unit/test_extensions/test_litestar/test_dto_integration.py, tests/unit/test_extensions/test_litestar/test_init_plugin/test_common.py, tests/unit/test_extensions/test_litestar/test_init_plugin/test_sync.py, tests/unit/test_extensions/test_starlette.py, uv.lock
Makes a few corrections to type hints in examples and tests to ensure 3.8 support
=> fix: correction for `3.8` and `3.9` type hints

docs/conf.py
Changed the default color of shibuya (purple) to amber to match Litestar color.
However, its the default color defined by Shibuya, maybe we have somewhere the colors used by the Litestar repo?
=> docs: update color theme to match litestar

advanced_alchemy/_listeners.py, advanced_alchemy/base.py, advanced_alchemy/filters.py, advanced_alchemy/mixins/audit.py, advanced_alchemy/repository/memory/_async.py, advanced_alchemy/repository/memory/_sync.py, docs/conf.py, docs/usage/frameworks/fastapi.rst, docs/usage/frameworks/litestar.rst, docs/usage/modeling.rst, docs/usage/repositories.rst, docs/usage/services.rst, examples/fastapi.py, examples/litestar/litestar_repo_only.py, examples/litestar/litestar_service.py, examples/sanic.py, tests/fixtures/bigint/models.py, tests/fixtures/uuid/models.py, tests/integration/helpers.py, tests/integration/test_repository.py, tests/unit/test_extensions/test_litestar/test_dto.py, tests/unit/test_repository.py
All date time references are now full qualified to prevent any forward resolution issues with
`from datetime import datetime`
and 
`import datetime`
=> fix: fully qualify all `datetime` module references

advanced_alchemy/service/_async.py, advanced_alchemy/service/_sync.py
The service layer has always has a `to_model` function that accepts data and optionally an operation name.  It would return a SQLAlchemy model no matter the input you gave it.
It is possible to move business logic into this `to_model` layer for populating fields on insert.  (i.e. slug fields or tags, etc.).
When having logic for `insert`, `update`, `delete`, and `upsert`, that function can be a bit overwhelcoming.  Now, there are helper functions that you can use that is specific to each DML hook:
* `to_model_on_create`
* `to_model_on_update`
* `to_model_on_delete`
* `to_model_on_upsert`
=> feat: add convenience hooks for `to_model` operations

advanced_alchemy/extensions/flask/config.py, docs/usage/frameworks/flask.rst, tests/unit/test_extensions/test_flask.py
The flask plugin incorrectly used the term `autocommit_with_redirect` instead of the existing `autocommit_include_redirect`.  
This changes makes the name consistent before we bump to a `1.x` release
=> fix: standardize on `autocommit_include_redirect`

advanced_alchemy/config/asyncio.py, advanced_alchemy/config/common.py, advanced_alchemy/config/sync.py
Adds hash function to `SQLAlchemySyncConfig` and `SQLAlchemyAsyncConfig` classes.
Closes #357
=> feat: add hash to config classes

README.md, docs/PYPI_README.md
Correct an invalid link to the updated FastAPI example
=> docs: correct invalid link to FastAPI example

advanced_alchemy/exceptions.py, advanced_alchemy/repository/_async.py, advanced_alchemy/repository/_sync.py, advanced_alchemy/repository/memory/_async.py, advanced_alchemy/repository/memory/_sync.py, advanced_alchemy/service/_async.py, advanced_alchemy/service/_sync.py, tests/unit/test_exceptions.py
When `wrap_exceptions` is `False`, the original SQLAlchemy error message will be raised instead of the wrapped Repository error
Fixes #356 (Bug: `wrap_sqlalchemy_exception` masks db errors)
=> feat: add `wrap_exceptions` option to exception handler.

advanced_alchemy/config/common.py
The hashing method on the SQLAlchemy configs can be simplified.  This should be enough to define a unique configuration.
=> feat: simplify configuration hash

.pre-commit-config.yaml, advanced_alchemy/config/common.py, advanced_alchemy/extensions/starlette/config.py, advanced_alchemy/extensions/starlette/extension.py, tests/unit/test_extensions/test_fastapi.py, tests/unit/test_extensions/test_starlette.py, uv.lock
Modifes the Starlette and FastAPI integrations to use the `lifespan` context manager instead of the `startup`\`shutdown` hooks.  If the application already has a lifespan set, it is wrapped so that both execute.
=> fix: use `lifespan` context manager in Starlette and FastAPI

docs/conf.py
Hello,
this add for the sibuya theme the discord link in the top bar
As we have a specific url in litestar discord, I can update the PR
I set the link to : https://discord.gg/dSDXd4mKhp
But we can use: https://discord.gg/litestar
That the message along the custom invite link.
=> docs: add discord link in navbar

docs/usage/cli.rst
This PR adds documentation regarding the integration into a Typer app
Closes #340
=> docs: add type integration example

docs/usage/cli.rst
This PR add a section inside the cli page on how to integrate the alchemy commands inside an existing group
=> docs: add documentation to integrate alchemy commands in an existing group

.github/workflows/ci.yml
Replace the deprecated sonar Github action with the new `sonarqube` action
=> chore(ci): use updated `sonarqube` scan action

.pre-commit-config.yaml, advanced_alchemy/_serialization.py, advanced_alchemy/extensions/litestar/plugins/init/plugin.py, advanced_alchemy/service/_typing.py, advanced_alchemy/service/_util.py, docs/conf.py, docs/usage/frameworks/fastapi.rst, examples/standalone_json.py, uv.lock
Extends the default `msgspec` type decoders to handle Enum types by converting them to their underlying value during serialization
=> feat: add Enum to default type decoders

.github/workflows/ci.yml
This PR adds the 3.13 to the test in the CI
pyproject file already had the 3.13.
@cofin I do not know how to update the badge in the README to remove 3.8 (shields.io)
Also, should I update the CI to run on 3.13 instead of 3.12  ? (type checking, etc)
=> chore: add 3.13 to test ci workflow

docs/conf.py
This PR set the minimum python version for examples to 3.9 instead of default 3.7
Also it set the maximum to 3.13 instead of default 3.12
=> docs: update autopytabs min version of python to 3.9 and max version to 3.13

.github/workflows/ci.yml, .github/workflows/docs.yml, .github/workflows/publish.yml, docs/usage/index.rst, sonar-project.properties, uv.lock
PR to update python version in CI from 3.12 to 3.13
=> chore(ci): Migrating from Python 3.12 to 3.13 in CI workflows

advanced_alchemy/extensions/litestar/providers.py
Remove unnecessary scoped session type hints from service provider functions.
Prevents the following exception from being incorrectly raised:
`TypeError: Type unions may not contain more than one custom type - type typing.Union[sqlalchemy.ext.asyncio.session.AsyncSession, sqlalchemy.ext.asyncio.scoping.async_scoped_session[sqlalchemy.ext.asyncio.session.AsyncSession], NoneType] is not supported.`
=> fix(litestar): simplify session type hints in service providers

advanced_alchemy/exceptions.py, advanced_alchemy/repository/_util.py, tests/unit/test_exceptions.py
Enhance the SQLAlchemy exception wrapper to handle NotFoundError with custom error messages and improved error handling. This includes:
- Adding a 'not_found' key to ErrorMessages type
- Extending wrap_sqlalchemy_exception to catch and handle NotFoundError
- Updating default error message templates with a not_found message
- Adding unit tests for custom NotFoundError handling
=> feat: allow custom `not_found` error messages

advanced_alchemy/extensions/sanic/__init__.py, advanced_alchemy/extensions/sanic/config.py, advanced_alchemy/extensions/sanic/extension.py, examples/sanic.py, pyproject.toml, sonar-project.properties, tests/unit/test_extensions/test_sanic.py
This commit refactors the Sanic extension for Advanced Alchemy:
- Refactored configuration handling with support for multiple database configurations
- Added methods for retrieving async and sync sessions, engines, and configs
- Improved dependency injection with new provider methods
- Simplified extension initialization and registration
- Updated example and test files to reflect new extension structure
- Removed deprecated methods and simplified the extension interface
=> feat(sanic)!: Refactor Sanic extension for multi-config support

advanced_alchemy/extensions/flask/extension.py, docs/usage/frameworks/flask.rst
Update the Flask example that uses the portal class.
Fixes #361
=> docs(flask): `async-in-sync` example should use the portal

.pre-commit-config.yaml, Makefile, advanced_alchemy/base.py, advanced_alchemy/exceptions.py, advanced_alchemy/extensions/sanic/config.py, advanced_alchemy/extensions/sanic/extension.py, advanced_alchemy/repository/_async.py, advanced_alchemy/repository/_sync.py, advanced_alchemy/repository/memory/base.py, advanced_alchemy/service/_util.py, pyproject.toml, uv.lock
This change applies the latest linting configurations and is the first 1.0 release candidate.
=> chore(release): bump to `v1.0.0`

advanced_alchemy/repository/_async.py, advanced_alchemy/repository/_sync.py, tests/unit/test_repository.py
Corrects the logic for using a count with a window function.
=> fix(repo): logic correction for window function

advanced_alchemy/extensions/litestar/dto.py, tests/unit/test_extensions/test_litestar/test_dto.py
Adds `sqlalchemy.orm.Relationship` to the supported type hints for the `SQLAlchemyDTO`
=> fix(dto): properly serialize `Relationship` type hints

advanced_alchemy/_serialization.py, advanced_alchemy/alembic/templates/asyncio/env.py, advanced_alchemy/alembic/templates/sync/env.py, advanced_alchemy/config/common.py, advanced_alchemy/extensions/litestar/dto.py, advanced_alchemy/extensions/litestar/providers.py, advanced_alchemy/extensions/sanic/config.py, advanced_alchemy/extensions/sanic/extension.py, advanced_alchemy/repository/_async.py, advanced_alchemy/repository/_sync.py, advanced_alchemy/repository/memory/_async.py, advanced_alchemy/repository/memory/_sync.py, advanced_alchemy/service/_async.py, advanced_alchemy/service/_sync.py, advanced_alchemy/utils/portals.py, advanced_alchemy/utils/singleton.py, advanced_alchemy/utils/sync_tools.py, examples/litestar/litestar_repo_only.py, examples/litestar/litestar_service.py, pyproject.toml, tests/unit/test_utils/test_sync_tools.py
Unquify is now correctly set when passed into the `new`/`init` methods.
Introduced tests for `sync_tools` utilities, including `maybe_async_`, `maybe_async_context`, `SoonValue`, `TaskGroup`, and others.
Improves coverage for async and sync function handling, context managers, and value management.
=> fix: correctly set `uniquify` from `new`

advanced_alchemy/alembic/templates/asyncio/env.py, advanced_alchemy/alembic/templates/sync/env.py
Removes column re-ordering component was incorrectly causing incorrect constraints to be genreated.
Fixes #427
=> fix(alembic): migration generation produces duplicated unique constraints

.github/workflows/docs.yml
Merged the build and deploy jobs into a single job named 'build_and_deploy' in the GitHub Actions workflow for documentation. This change simplifies the workflow and ensures that deployment occurs immediately after the build process, improving efficiency.
=> chore(ci): updated docs deployment

advanced_alchemy/repository/_async.py, advanced_alchemy/repository/_sync.py, advanced_alchemy/repository/_util.py, advanced_alchemy/repository/memory/_async.py, advanced_alchemy/repository/memory/_sync.py, advanced_alchemy/repository/typing.py, tests/integration/test_repository.py
Enables the standard `UnaryOperator` order by support in addition to the existing `OrderingPair`
=> feat: enable standard order by

advanced_alchemy/mixins/sentinel.py
`MappedAsDataclass` is a mixin introduced in SQLAlchemy 2.0. It introduces massive DX improvements to SQLAlchemy by introducing dataclass type validation to SQLAlchemy models. However, this mixin is incompatible with SQLAlchemy's recommended method of implementing a sentinel column as written in their [documentation](https://docs.sqlalchemy.org/en/20/core/connections.html#configuring-sentinel-columns).
This PR fixes this incompatibility as suggested by the SQLAlchemy maintainer in this [discussion](https://github.com/sqlalchemy/sqlalchemy/discussions/12519#discussioncomment-12804658).
=> fix: make `SentinelMixin` compatible with `MappedAsDataclass`

advanced_alchemy/extensions/litestar/providers.py, tests/unit/test_extensions/test_litestar/test_providers.py
This change allows for arguments to also be matched when generating a service provider closure.
=> feat: allows positional args for session

advanced_alchemy/repository/_async.py, advanced_alchemy/repository/_sync.py
Passing `uniquify` as an `__init__` argument now works as expected.
=> fix: `uniquify` respects init method override

advanced_alchemy/repository/_async.py, advanced_alchemy/repository/_sync.py, advanced_alchemy/repository/memory/_async.py, advanced_alchemy/repository/memory/_sync.py, advanced_alchemy/service/_async.py, advanced_alchemy/service/_sync.py
This change fixes the type hint for the `with_for_update` parameter in the repositories. Currently, the type hint is `Optional[bool]`, but according to the method's docstring, `with_for_update` is described as: "_indicating FOR UPDATE should be used, or may be a dictionary containing flags to indicate a more specific set of FOR UPDATE flags for the SELECT_". This implies that a dictionary may be passed, but the current type hint doesn’t reflect that.
If we trace where `with_for_update` is passed, it ends up unchanged in session.refresh in SQLAlchemy, which has the type hint `ForUpdateParameter = Union["ForUpdateArg", None, bool, Dict[str, Any]]`, and that’s what I updated the type hints in our code to match.
However, it’s possible that this isn’t what was originally intended, and I’m not …
=> fix(types): correct type hints for with_for_update to ForUpdateParameter

.pre-commit-config.yaml, advanced_alchemy/base.py, advanced_alchemy/mixins/__init__.py, advanced_alchemy/mixins/bigint.py, docs/usage/modeling.rst, tests/integration/test_bigint_identity.py, uv.lock
The sequences based BigInt key offers the most compatibility, but many would prefer to use the Identity column when the database supports it.
This changes implements a basic Identity primary key mixin
=> feat: Add identity Mixin for Primary Keys

advanced_alchemy/repository/_async.py, advanced_alchemy/repository/_sync.py
`wrap_exceptions` is now correctly passed into the exception handler context manager.
Fixes #472
=> fix: `wrap_exceptions` is re-enabled

advanced_alchemy/service/__init__.py, advanced_alchemy/service/_async.py, advanced_alchemy/service/_sync.py, advanced_alchemy/service/_typing.py, advanced_alchemy/service/_util.py, advanced_alchemy/service/typing.py, docs/changelog.rst, docs/usage/services.rst, pyproject.toml, tests/integration/test_attrs_service.py, tests/unit/test_attrs_integration.py, tests/unit/test_cattrs_integration.py, uv.lock
Adds `attrs` support into the `ResultConverter` mixin.  This enables `to_schema` and `schema_dump` to natively understand `attrs`.
=> feat: `attrs` integration

advanced_alchemy/mixins/nanoid.py, advanced_alchemy/mixins/uuid.py
- Add warning message when using `uuid` instead of `nanoid`
- Add warning message when using `uuid4` instead of `uuid6` or `uuid7`
=> fix: add warning message when using fallback value for a primary key

advanced_alchemy/types/file_object/backends/obstore.py, tests/integration/test_file_object.py
The `ObstoreBackend` was not passing `content_type` from `FileObject` to the underlying storage backend. When saving files through obstore to cloud storage providers (S3, GCS, Azure), the `Content-Type` header was not being set, resulting in files stored without proper MIME types.
The `save_object` and `save_object_async` methods called `fs.put()` and `fs.put_async()` without the `attributes` parameter. According to the obstore API, object metadata like `Content-Type` must be passed via this parameter.
**Backend (`advanced_alchemy/types/file_object/backends/obstore.py`):**
- Modified `save_object` and `save_object_async` methods to collect attributes from `FileObject`
- Pass `content_type` as `"Content-Type"` in the `attributes` parameter
- Include any custom metadata from …
=> fix(obstore): pass Content-Type and metadata to backend storage

advanced_alchemy/repository/_async.py, advanced_alchemy/repository/_sync.py, tests/unit/test_repository.py
Correctly handle `viewownly` and `lazy` loaded relationships during update.
=> fix: correctly handle lazy attributes on update

advanced_alchemy/repository/_async.py, advanced_alchemy/repository/_sync.py, tests/unit/test_repository.py
This fixes #552 by moving the guard condition up. One test has been modified but honestly I'm less certain about the test change than the code change lol.
=> fix: lazy attributes getting accessed on repository update method
